apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-config
  namespace: dns
data:
  Corefile: |
    .:53 {
        errors
        health :8080
        ready :8181

        file /etc/coredns/zones/{$BASE_DOMAIN}.zone {$BASE_DOMAIN}

        forward . tls://9.9.9.9 tls://149.112.112.112 {
            tls_servername dns.quad9.net
            health_check 5s
        }

        cache 30
        loop
        reload 5s
        log
    }
