name: traefik

services:
  traefik:
    image: traefik:v3.2
    container_name: traefik
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "traefik", "healthcheck", "--ping"]
      interval: 30s
      timeout: 5s
      retries: 3
    security_opt:
      no-new-privileges: true
    environment:
      TZ: ${TZ:-Europe/Paris}

    volumes:
      - ${CONTAINER_ENGINE_SOCKET:-/run/user/1000/podman/podman.sock}:/var/run/docker.sock:ro
      - ./config/dynamic/:/etc/traefik/dynamic/:ro
      - ./certs:/certs:ro

    networks:
      - proxy
    ports:
      - 80:80
      - 443:443

    labels:
      # Enable self-routing
      traefik.enable: "true"

      # Dashboard router
      traefik.http.routers.dashboard.rule: "Host(`traefik.${BASE_DOMAIN:?BASE_DOMAIN required}`)"
      traefik.http.routers.dashboard.entrypoints: websecure
      traefik.http.routers.dashboard.tls.certresolver: letsencrypt
      traefik.http.routers.dashboard.service: api@internal
      traefik.http.routers.dashboard.tls: true

    command:
      # API & Dashboard
      - --api.dashboard=true
      - --api.insecure=false

      # Entrypoints
      - --entrypoints.web.address=80
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --entrypoints.web.http.redirections.entrypoint.permanent=true
      - --entrypoint.websecure.address=:443
      


volumes:
  traefik-certs:

networks:
  proxy:
    external: true
